### PR TITLE
Remove GUI components.

### PR DESCRIPTION
**Pull request by sinetek**
Try #3. Remove GUI/Qt completely as we don't need it, and it slows things down, notably the build dependencies.

### CODE REVIEW

**Comment by sinetek** [comment]
I will rework the commit text on next push.

**Comment by sinetek** [comment]
Windows build fails.
```fatal error C1083: Cannot open include file: 'bls/bls384_256.h': No such file or directory ```

**Comment by sinetek** [comment]
> Windows build fails. `fatal error C1083: Cannot open include file: 'bls/bls384_256.h': No such file or directory `

This is fixed in [a9a5593](https://github.com/navcoin/navcoin/pull/72/commits/a9a55936999321fce8b77a58c45e263ca0ae25d1). @mxaddict  @aguycalled  Can you review this for inclusion?

**Comment by aguycalled** [comment]
I don't have a windows dev environment, but from the look of it, it's proof enough if it removes the issue in your env

**Review by mxaddict — APPROVED** [review]

**Pull request merged**
